/*
 * File: app/view/InfoDialog.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
Ext.define('AccountMgmt.view.InfoDialog', {
  extend: 'Ext.window.Window',
  alias: 'widget.infodialog',

  requires: [
    'AccountMgmt.view.InfoDialogViewController',
    'AccountMgmt.view.InfoDialogViewModel',
    'Common.ux.CustomVTypes'
  ],

  controller: 'infodialog',
  viewModel: {
    type: 'infodialog'
  },
  height: 410,
  width: 360,
  layout: 'fit',
  iconCls: 'permission',
  constrainHeader: true,
  modal: true,
  title: '账号信息',

  items: [
    {
      xtype: 'form',
      reference: 'form',
      border: false,
      scrollable: 'y',
      defaults: {
        anchor: '100%',
        labelWidth: 70
      },
      bodyPadding: '10 10 10 15',
      title: '',
      items: [
        {
          xtype: 'textfield',
          itemId: "name",
          fieldLabel: '姓名<span style="color:red">*</span>',
          allowBlank: false,
          bind: {
            value: "{formData.name}",
            readOnly:'{isView}'
          }
        },
        {
          xtype: 'textfield',
          itemId: "post",
          fieldLabel: '职务',
          bind: {
            value: "{formData.post}",
            readOnly:'{isView}'
          }
        },
        {
          xtype: 'textfield',
          itemId: "phoneNum",
          fieldLabel: '手机号',
          regex: /^[\s\S]{0,20}$/,
          regexText:'手机号长度应在20个字符以内',
          bind: {
            value: "{formData.phoneNum}",
            readOnly:'{isView}'
          }
        },
        {
          xtype:'combobox',
          fieldLabel: '所属公司(团队)<span style="color:red">*</span>',
          emptyText: "请选择",
          editable: false,
          allowBlank: false,
          name:'companyId',
          displayField:'value',
          valueField:'key',
          itemId: 'companyId',
          bind:{
            store:'{companycomboboxstore}',
            value: "{formData.companyName}",
            readOnly:'{isView}'
          }
        },
        {
          xtype: 'textfield',
          itemId: "companyCode",
          fieldLabel: '公司(团队)代码',
          bind: {
            readOnly:true,
            value: "{formData.companyCode}",
            readOnly:'{isView}'
          }
        },
        {
          xtype:'combobox',
          fieldLabel: '用户角色<span style="color:red">*</span>',
          emptyText: "请选择",
          editable: false,
          allowBlank: false,
          name:'roleId',
          displayField:'value',
          valueField:'type',
          store:'RoleComboboxStore',
          queryMode:'local',
          itemId: 'roleId',
          bind: {
            value: "{formData.roleName}",
            readOnly:'{isView}'
          }
        },
        {
          xtype: 'textfield',
          itemId: "userName",
          fieldLabel: '用户名<span style="color:red">*</span>',
          allowBlank: false,
          blankText: '该字段必填项',
          regex: /^[a-zA-Z\d_]{4,20}$/i,
          regexText:'登录名长度应在4~20个字符之间，且由英文、数字及“_”自由组合',
          bind: {
            value: "{formData.userName}",
            disabled: true
          }
        },
        {
          xtype: 'textfield',
          fieldLabel: '登录密码<span style="color:red">*</span>',
          reference: "newPassword",
          //inputType: 'password',
          allowBlank: false,
          blankText: "请输入密码",
          name:'newPassword',
          //regex: /^[a-zA-Z\d\~\`\!\@\#\$\%\^\&\*\(\)\-\_\+\=\|\\\[\]\{\}\;\:\"\'\,\<\.\>\/\?]{6,20}$/i,
          regex: /^[\s\S]{6,20}$/i,
          regexText:'登录密码长度应在6~20个字符之间，且由英文、数字及标点符号组成',
          bind: {
            value: "{formData.password}",
            readOnly:'{isView}'
          }
        },
        {
          xtype: 'textareafield',
          height: 76,
          width: 400,
          name:'remark',
          fieldLabel: '备注',
          bind: {
            value: "{formData.remark}",
            readOnly:'{isView}'
          }
        },
        /*{
          xtype: 'textfield',
          reference: "confirmPassword",
          name: "confirmPassword",
          fieldLabel: '再次输入<span style="color:red">*</span>',
          inputType: 'password',
          allowBlank: false,
          blankText: "请输入密码",
          vtype:'repetitionCustom',
          repetition: {targetName: 'newPassword'},
          bind: {
            value: "{formData.confirmPassword}",
            disabled: "{!addFlag}",
            hidden: "{!addFlag}"
          }
        },*/

        /*{
          xtype: 'fieldcontainer',
          height: 25,
          fieldLabel: '',
          items: [
            {
              xtype: 'checkboxgroup',
              width: 115,
              fieldLabel: '',
              columns: 2,
              items: [
                {
                  xtype: 'checkboxfield',
                  boxLabel: '锁定',
                  reference: "locked"
                }, {
                  xtype: 'checkboxfield',
                  boxLabel: '管理员',
                  reference: "isAdmin"
                }
              ]
            }
          ]
        }*/
      ]
    }
  ],
  dockedItems: [
    {
      xtype: 'toolbar',
      dock: 'bottom',
      ui: 'footer',
      items: [
        {
          xtype: 'tbfill'
        },
        {
          xtype: 'button',
          iconCls: 'btn-save',
          text: '保存',
          listeners: {
            click: 'onSaveButtonClick'
          },
          bind:{
            hidden:"{isView}"
          }
        },
        {
          xtype: 'button',
          iconCls: 'btn-cancel',
          text: '取消',
          listeners: {
            click: 'onCancelButtonClick'
          }
        }
      ]
    }
  ]

});