/*
 * File: app/view/InfoDialogViewController.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AccountMgmt.view.InfoDialogViewController', {
  extend: 'Ext.app.ViewController',
  alias: 'controller.infodialog',

  requires: [

  ],

  init: function() {
    this.getViewModel().set("formData", {
      id:'',
      name:'',
      post:'',
      phoneNum:'',
      companyId:'',
      companyName:'',
      companyCode:'',
      roleId:'',
      roleName:'',
      userName:'',
      password:'',
      remark:''
    });
  },
  /**
   * 保存
   */
  onSaveButtonClick: function (button, e, eOpts) {
    var viewCtr = this,
        currWin = viewCtr.getView(),
        viewModel = this.getViewModel(),
        formCmp = currWin.down("form");

    if (!formCmp.isValid()) {
      TipsUtil.showTips("提示", "信息填写有误", TipsUtil.WARING);
      return ;
    }

    var formData = viewModel.get("formData");
    console.info(formData);
    var requestFormData = Ext.clone(formData);

    var url = FACADE_URL+'/account/';

    if(formData.id) {
      Ext.Ajax.request({
        method: 'POST',
        url: url+'update',
        params: requestFormData,
        success: function (request) {
          if (request.responseText) {
            var json = Ext.decode(request.responseText);
            if (json.success) {
              //console.info(json);
              currWin.close();
              Ext.StoreMgr.get('mainViewPortGridStore').load();
              //viewModel.getStore("mainviewstore").load();
              return;
            } else {
              TipsUtil.showTips("错误", json.error.message || "服务器错误！");
            }
          }
        }
      });
    } else {
      url += '/user/add';
    }


  },


  /**
   * 取消
   */
  onCancelButtonClick: function (button, e, eOpts) {
    var viewCtr = this;

    viewCtr.getView().close();
  }

});
