/*
 * File: app/view/InfoDialog.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
Ext.define('CategoryMgmt.view.InfoDialog', {
  extend: 'Ext.window.Window',
  alias: 'widget.infodialog',

  requires: [
    'CategoryMgmt.view.InfoDialogViewController',
    'CategoryMgmt.view.InfoDialogViewModel',
    'Common.ux.CustomVTypes'
  ],

  controller: 'infodialog',
  viewModel: {
    type: 'infodialog'
  },
  height: 410,
  width: 450,
  layout: 'fit',
  iconCls: 'permission',
  constrainHeader: true,
  modal: true,
  title: '公司信息',

  items: [
    {
      xtype: 'form',
      reference: 'form',
      border: false,
      scrollable: 'y',
      defaults: {
        anchor: '100%',
        labelWidth: 125
      },
      bodyPadding: '10 10 10 15',
      title: '',
      items: [
        {
          xtype: 'textfield',
          itemId: "name",
          fieldLabel: '公司(团队)名称<span style="color:red">*</span>',
          allowBlank: false,
          bind: {
            value: "{formData.name}",
            readOnly:'{isView}'
          }
        },
        {
          xtype: 'textfield',
          itemId: "code",
          fieldLabel: '公司(团队)代码<span style="color:red">*</span>',
          bind: {
            value: "{formData.code}",
            readOnly:'{isView}'
          }
        },
        {
          xtype: 'textfield',
          itemId: "shortName",
          fieldLabel: '公司(团队)简称',
          bind: {
            value: "{formData.shortName}",
            readOnly:'{isView}'
          }
        },
        {
          xtype: 'textfield',
          itemId: "introduce",
          fieldLabel: '公司(团队)介绍',
          bind: {
            value: "{formData.introduce}",
            readOnly:'{isView}'
          }
        },
        {
          xtype: 'textfield',
          itemId: "address",
          fieldLabel: '公司(团队)地址',
          bind: {
            value: "{formData.address}",
            readOnly:'{isView}'
          }
        },
        {
          xtype: 'textfield',
          name:'phone',
          fieldLabel: '公司(团队)电话',
          //regex: /^1[3|4|5|7|8]\d{9}$/,
          //regexText:'手机号格式错误',
          bind: {
            value: "{formData.phone}",
            readOnly:'{isView}'
          }
        },
        {
          xtype: 'textareafield',
          height: 76,
          width: 400,
          name:'remark',
          fieldLabel: '备注',
          bind: {
            value: "{formData.remark}",
            readOnly:'{isView}'
          }
        },
        /*{
          xtype: 'textfield',
          reference: "confirmPassword",
          name: "confirmPassword",
          fieldLabel: '再次输入<span style="color:red">*</span>',
          inputType: 'password',
          allowBlank: false,
          blankText: "请输入密码",
          vtype:'repetitionCustom',
          repetition: {targetName: 'newPassword'},
          bind: {
            value: "{formData.confirmPassword}",
            disabled: "{!addFlag}",
            hidden: "{!addFlag}"
          }
        },*/

        /*{
          xtype: 'fieldcontainer',
          height: 25,
          fieldLabel: '',
          items: [
            {
              xtype: 'checkboxgroup',
              width: 115,
              fieldLabel: '',
              columns: 2,
              items: [
                {
                  xtype: 'checkboxfield',
                  boxLabel: '锁定',
                  reference: "locked"
                }, {
                  xtype: 'checkboxfield',
                  boxLabel: '管理员',
                  reference: "isAdmin"
                }
              ]
            }
          ]
        }*/
      ]
    }
  ],
  dockedItems: [
    {
      xtype: 'toolbar',
      dock: 'bottom',
      ui: 'footer',
      items: [
        {
          xtype: 'tbfill'
        },
        {
          xtype: 'button',
          iconCls: 'btn-save',
          text: '保存',
          listeners: {
            click: 'onSaveButtonClick'
          },
          bind:{
            hidden:"{isView}"
          }
        },
        {
          xtype: 'button',
          iconCls: 'btn-cancel',
          text: '取消',
          listeners: {
            click: 'onCancelButtonClick'
          }
        }
      ]
    }
  ]

});