/*
 * File: app/view/LogDiffDialog.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Common.view.order.LogDiffDialog', {
  extend: 'Ext.window.Window',
  alias: 'widget.order.logdiffdialog',

  requires: [
    'Common.view.order.LogDiffDialogViewModel',
    'Common.view.order.LogDiffDialogViewController',
    'Ext.form.field.Number',
    'Ext.button.Button',
    'Ext.grid.Panel',
    'Ext.view.Table',
    'Ext.grid.column.RowNumberer',
    'Ext.toolbar.Toolbar',
    'Ext.toolbar.Fill'
  ],

  controller: 'order.logdiffdialog',
  viewModel: {
    type: 'order.logdiffdialog'
  },
  height: 288,
  width: 500,
  minWidth:490,
  bodyStyle: 'background-color:white;',
  modal: true,
  autoShow: true,
  title: '日志差异比较',

  layout: {
    type: 'border',
    padding: '10 5 5 5'
  },
  items: [
    {
      xtype: 'container',
      region: 'north',
      height: 28,
      defaults: {
        width: 165,
        labelWidth: 65,
        margin: '0 5 5 0'
      },
      layout: {
        type: 'table',
        columns: 3
      },
      items: [
        {
          xtype: 'numberfield',
          fieldLabel: '版本号'
        },
        {
          xtype: 'numberfield',
          fieldLabel: '新版本号'
        },
        {
          xtype: 'button',
          width: 80,
          iconCls: 'btn-add',
          text: '差异比较',
          listeners: {
            click: 'onButtonDiffClick'
          }
        }
      ]
    },
    {
      xtype: 'gridpanel',
      region: 'center',
      title: '',
      bind: {
        store: '{logdiffgridstore}'
      },
      columns: [
        {
          xtype: 'rownumberer',
          width: 37,
          align: 'center',
          text: '序号'
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'A01',
          text: '修改字段名'
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'A02',
          text: '修改前内容'
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'A03',
          text: '修改后内容'
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'A04',
          text: 'A04'
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'A05',
          text: 'A05'
        }
      ]
    }
  ],
  dockedItems: [
    {
      xtype: 'toolbar',
      dock: 'bottom',
      ui: 'footer',
      items: [
        {
          xtype: 'tbfill'
        },
        {
          xtype: 'button',
          icon: '',
          iconCls: 'btn-cancel',
          text: '关闭',
          listeners: {
            click: 'onButtonCloseClick'
          }
        }
      ]
    }
  ]

});