/*
 * File: app/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('addCategory.view.MainWindow', {
  extend: 'Ext.window.Window',
  alias: 'widget.mainwindow',

  requires: [
    'addCategory.view.MainWindowViewController',
    'addCategory.view.MainWindowViewModel',
    'Common.ux.NumberFieldCustom',
    'Ext.form.Panel',
    'Ext.form.field.Display',
    'Ext.form.field.ComboBox',
    'Ext.form.CheckboxGroup',
    'Ext.form.field.Number',
    'Ext.form.field.Checkbox'
  ],

  controller: 'mainwindow',
  viewModel: {
    type: 'mainwindow'
  },
  autoShow: true,
  height: 480,
  width: 460,
  layout: 'fit',
  title: '新增分类',
  closable:false,

  items: [
    {
      xtype: 'form',
      flex: 1,
      defaults: {
        flex: 0.5
      },
      bodyPadding: 10,
      header: false,
      title: 'My Form',
      layout: {
        type: 'hbox',
        align: 'stretch'
      },
      items: [
        {
          xtype: 'fieldcontainer',
          flex: 1,
          height: 120,
          width: 400,
          defaults: {
            columnWidth: 1,
            margin: '2 20 20 20'
          },
          layout: 'column',
          fieldLabel: '',
          items: [
            {
              xtype: 'combobox',
              fieldLabel: '所属栏目<span style="color:red">*</span>',
              allowBlank: false,
              editable: false,
              name: 'columnCode',
              queryMode: 'local',
              displayField: 'value',
              valueField: 'key',
              store:'ColumnComboboxStore',
              listeners:{
                change:'onColumnChange'
              }
            },
            {
              xtype: 'combobox',
              editable: false,
              fieldLabel: '上级分类',
              queryMode: 'local',
              displayField: 'value',
              valueField: 'key',
              id:'categoryComboxStore',
              name:'upClassId',
              bind:{
                store:'{categorycomboboxstore}'
              }
            },
            {
              xtype: 'textfield',
              name:'name',
              fieldLabel: '分类名称'
            }



          ]
        }
      ]
    }
  ],
  dockedItems: [
    {
      xtype: 'toolbar',
      dock: 'bottom',
      ui: 'footer',
      items: [
        {
          xtype: 'tbfill'
        },
        {
          xtype: 'button',
          iconCls: 'btn-save',
          text: '保存',
          listeners: {
            click: 'onSaveButtonClick'
          }
        },
        {
          xtype: 'button',
          iconCls: 'btn-cancel',
          text: '重置',
          handler: function() {
            this.ownerCt.ownerCt.down('form').getForm().reset()
          }
        }
      ]
    }
  ]
});