/*
 * File: app/store/TemplateTypeStore.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StockTaking.store.StockTakingStatusStore', {
    extend: 'Ext.data.ArrayStore',

    requires: [
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'StockTakingStatusStore',
            fields:['key','value'],
            data: [
                {
                    key: 'DRAFT',
                    value: '草稿'
                },
                {
                    key: 'PENDING_APPROVE',
                    value: '待审核'
                },
                {
                    key: 'APPROVED',
                    value: '审核通过'
                },
                {
                    key: 'CANCELLED',
                    value: '已取消'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'array'
                }
            }
        }, cfg)]);
    }
});