/*
 * File: app/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('addCompany.view.MainWindow', {
  extend: 'Ext.window.Window',
  alias: 'widget.mainwindow',

  requires: [
    'addCompany.view.MainWindowViewController',
    'addCompany.view.MainWindowViewModel',
    'Common.ux.NumberFieldCustom',
    'Ext.form.Panel',
    'Ext.form.field.Display',
    'Ext.form.field.ComboBox',
    'Ext.form.CheckboxGroup',
    'Ext.form.field.Number',
    'Ext.form.field.Checkbox'
  ],

  controller: 'mainwindow',
  viewModel: {
    type: 'mainwindow'
  },
  autoShow: true,
  height: 540,
  width: 810,
  layout: 'fit',
  title: '新增公司',
  closable:false,

  items: [
    {
      xtype: 'form',
      flex: 1,
      defaults: {
        flex: 0.5
      },
      bodyPadding: 10,
      header: false,
      title: 'My Form',
      layout: {
        type: 'hbox',
        align: 'stretch'
      },
      items: [
        {
          xtype: 'fieldcontainer',
          flex: 1,
          height: 120,
          width: 400,
          defaults: {
            columnWidth: 1,
            margin: '2 20 20 20'
          },
          layout: 'column',
          fieldLabel: '',
          items: [
            {
              xtype: 'textfield',
              name:'name',
              fieldLabel: '公&nbsp;司&nbsp;名&nbsp;称<span style="color:red">*</span>',
              allowBlank: false
            },
            {
              xtype: 'textfield',
              name:'code',
              fieldLabel: '公&nbsp;司&nbsp;代&nbsp;码<span style="color:red">*</span>',
              allowBlank: false
            },
            {
              xtype: 'textfield',
              name:'shortName',
              fieldLabel: '公&nbsp;司&nbsp;简&nbsp;称&nbsp;'
            },

            {
              xtype: 'textfield',
              name:'address',
              fieldLabel: '公&nbsp;司&nbsp;地&nbsp;址&nbsp;'
            },
            {
              xtype: 'textfield',
              name:'phone',
              fieldLabel: '公&nbsp;司&nbsp;电&nbsp;话&nbsp;',
              //regex: /^1[3|4|5|7|8]\d{9}$/,
              //regexText:'手机号格式错误'
            },
            {
              xtype: 'textareafield',
              height: 76,
              width: 400,
              name:'introduce',
              fieldLabel: '公&nbsp;司&nbsp;介&nbsp;绍&nbsp;'
            },{
              xtype: 'textareafield',
              height: 76,
              width: 400,
              name:'remark',
              fieldLabel: '备&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;注&nbsp;'
            },

          ]
        }
      ]
    }
  ],
  dockedItems: [
    {
      xtype: 'toolbar',
      dock: 'bottom',
      ui: 'footer',
      items: [
        {
          xtype: 'tbfill'
        },
        {
          xtype: 'button',
          iconCls: 'btn-save',
          text: '保存',
          listeners: {
            click: 'onSaveButtonClick'
          }
        },
        {
          xtype: 'button',
          iconCls: 'btn-cancel',
          text: '重置',
          handler: function() {
            this.ownerCt.ownerCt.down('form').getForm().reset()
          }
        }
      ]
    }
  ]
});