/*
 * File: app/view/StockTakingViewport.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StockTaking.view.StockTakingViewport', {
  extend: 'Ext.container.Viewport',
  alias: 'widget.stocktakingviewport',

  requires: [
    'StockTaking.view.StockTakingViewportViewModel',
    'StockTaking.view.StockTakingViewportViewController',
    'StockTaking.view.DownloadStockTakingWindow',
    'StockTaking.view.UploadStockTakingResultWindow',
    'StockTaking.view.StockTakingDetailWindow',
    'Ext.grid.Panel',
    'Ext.view.Table',
    'Ext.toolbar.Toolbar',
    'Ext.form.field.ComboBox',
    'Ext.form.field.Date',
    'Ext.button.Button',
    'Ext.grid.column.RowNumberer',
    'Ext.grid.column.Widget',
    'Ext.grid.column.Number'
  ],

  controller: 'stocktakingviewport',

  viewModel: {
    type: 'stocktakingviewport'
  },
  layout: 'fit',

  items: [
    {
      xtype: 'gridpanel',
      header: false,
      store: 'GridStore',
      dockedItems: [
        {
          xtype: 'form',
          dock: 'top',
          layout: {
            type: 'hbox',
            align: 'stretch'
          },
          defaultButton: 'searchBtn',
          bodyPadding: 5,
          header: false,
          border: false,
          defaults: {
            flex: 2,
            labelWidth: 80,
            margin: 5,
            handler: "onCommandColumnClick"
          },
          items: [
            {
              xtype: 'combobox',
              name: 'whsId',
              fieldLabel: '仓库',
              emptyText: '请选择',
              editable: false,
              queryMode: 'local',
              displayField: 'name',
              valueField: 'id',
              bind: {
                store: '{commonwhsstore}'
              }
            },
            {
              xtype: 'combobox',
              fieldLabel: '盘点状态',
              editable: false,
              name:'status',
              store: 'StockTakingStatusStore',
              queryMode: 'local',
              displayField: 'value',
              emptyText: '请选择 (默认不展示已取消)',
              valueField: 'key'
            },
            {
              xtype: 'datefield',
              fieldLabel: '盘点时间',
              editable: false,
              name: 'stockTakingDateFrom',
              format: 'Y/n/j',
              bind: {
                value: '{dateFrom}',
                maxValue:'{dateTo}'
              }
            },
            {
              xtype: 'datefield',
              fieldLabel: '至',
              editable: false,
              name: 'stockTakingDateTo',
              format: 'Y/n/j',
              bind: {
                value: '{dateTo}',
                minValue:'{dateFrom}'
              }
            },
            {
              xtype: 'button',
              reference: 'searchBtn',
              text: '查询',
              iconCls: 'btn-search',
              command: 'search',
              flex: 1
            },
            {
              xtype: 'button',
              text: '清空',
              iconCls: 'btn-clear',
              command: 'empty',
              flex: 1
            }
          ]
        },
        {
          xtype: 'toolbar',
          dock: 'top',
          defaults: {
            handler: "onCommandColumnClick"
          },
          items: [
            {
              xtype: 'button',
              text: '下载盘点单',
              iconCls: 'page-excel',
              command: 'downLoad'
            },
            {
              xtype: 'button',
              iconCls: 'page-add',
              text: '上传盘点结果',
              command: 'upLoad',
              bind:{
                disabled: '{buttonDisable}'
              }
            },
            {
              xtype: 'button',
              text: '手工开单',
              iconCls: 'btn-form-add',
              command: 'manulAdd',
              bind:{
                disabled: '{buttonDisable}'
              }
            }
          ]
        },
        {
          xtype: 'pagingtoolbar',
          dock: 'bottom',
          displayInfo: true,
          store: 'GridStore',
          plugins: [
            Ext.create("Ext.ux.ProgressBarPager"),
            Ext.create("Common.ux.PagingToolbarResizer", {})
          ]
        }
      ],
      columns: {
        defaults: {
          cls:'titleAlign',
          align: 'center',
          tdCls: 'with-btngroup',
          sortable: false
        },
        items: [
          {
            xtype: 'rownumberer',
            width: 50,
            text: '序号'
          },
          {
            xtype: 'widgetcolumn',
            text: '操作',
            tdCls: 'btngroup',
            width: 120,
            dataIndex: 'progress',
            widget: {
              xtype: 'buttongroup',
              baseCls: '',
              defaultBindProperty: 'operation',
              setOperation: function () {
                this.removeAll();
                this.add(this.lookupViewModel().get('statusButton')[this.getWidgetRecord().get('status')]);
              },
              layout: {
                type: 'column'
              },
              defaults: {
                handler: 'onCommandColumnClick'
              }
            }
          },
          {
            xtype: 'gridcolumn',
            dataIndex: 'postDate',
            formatter: 'date("Y/m/d")',
            text: '盘点时间'
          },
          {
            xtype: 'gridcolumn',
            dataIndex: 'approvedDate',
            formatter: 'date("Y/m/d H:i:s")',
            text: '审核通过时间'
          },
          {
            xtype: 'gridcolumn',
            dataIndex: 'takingNo',
            text: '盘点单号',
            width: 170,
            align: 'left'
          },
          {
            xtype: 'gridcolumn',
            dataIndex: 'type',
            text: '盘点类型',
            renderer: 'renderType'
          },
          {
            xtype: 'gridcolumn',
            dataIndex: 'whsName',
            text: '仓库名称',
            align: 'left'
          },
          {
            xtype: 'gridcolumn',
            dataIndex: 'createByName',
            text: '盘点人',
            align: 'left'
          },
          {
            xtype: 'gridcolumn',
            dataIndex: 'approvedByName',
            text: '审核人',
            align: 'left'
          },
          {
            xtype: 'gridcolumn',
            dataIndex: 'status',
            text: '盘点状态',
            renderer: 'renderStatus'
          },
          {
            xtype: 'gridcolumn',
            dataIndex: 'totalBeforeQty',
            text: '实际库存数',
            align: 'right'
          },
          {
            xtype: 'gridcolumn',
            dataIndex: 'totalAfterQty',
            text: '盘点数量',
            align: 'right'
          },
          {
            xtype: 'gridcolumn',
            dataIndex: 'totalDifferenceQty',
            text: '差异数量',
            align: 'right'
          },
          {
            xtype: 'numbercolumn',
            dataIndex: 'totalDifferencePrice',
            text: '盘点差异总额',
            align: 'right'
          },
          {
            xtype: 'gridcolumn',
            dataIndex: 'memo',
            flex: 1 ,
            text: '备注',
            align: 'left'
          }
        ]
      }
    }
  ]

});