/*
 * File: app/store/AccountMgmtBranchComboStore.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('addCategory.store.ColumnComboboxStore', {
  extend: 'Ext.data.ArrayStore',
  alias: 'store.columncomboboxstore',

  requires: [
    'Ext.data.proxy.Ajax',
    'Ext.data.reader.Json'
  ],

  constructor: function (cfg) {
    var me = this;
    cfg = cfg || {};
    me.callParent([Ext.apply({
      storeId:'ColumnComboboxStore',
      fields:['key','value'],
      data: [
        {
          key: '0001',
          value: '信息披露'
        },
        {
          key: '0002',
          value: '学习园地'
        },
        {
          key: '0003',
          value: '市场咨询'
        },
        {
          key: '0004',
          value: '通知公告'
        }
      ],
      proxy: {
        type: 'ajax',
        reader: {
          type: 'array'
        }
      }
      /*proxy: {
        type: 'ajax',
        url: '/api/general/role/related/filter',
        extraParams: {
          //type: cfg.comboxType
        },
        api: {
          create  : "/api/general/role/related/add",
          read    : "/api/general/role/related/filter",
          update  : "/api/general/role/related/update",
          destroy : "/api/general/role/related/delete"
        },
        reader: {
          type: 'json',
          rootProperty: 'data'
        },
        headers: {
          "Content-Type":"application/x-www-form-urlencoded; charset=UTF-8"
        },
        writer: {
          type: 'json',
          transform: {
            fn: function(data, request) {
              return Ext.Object.toQueryString(data);
            },
            scope: this
          }
        }
      }*/
    }, cfg)]);
  }
});