/*
 * File: app/view/MainViewport.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AccountMgmt.view.MainViewport', {
  extend: 'Ext.container.Viewport',
  alias: 'widget.mainviewport',

  requires: [
    'AccountMgmt.view.MainViewportViewController',
    'AccountMgmt.view.MainViewportViewModel',
    'Common.ux.CommandColumn'

  ],

  controller: 'mainviewport',
  viewModel: {
    type: 'mainviewport'
  },
  layout: 'fit',

  items: [{
    xtype: 'gridpanel',
    title: '帐号管理主页',
    //columnLines: true,
    reference: "accountMgmtGrid",
    header: false,
    bind: {
      store: "{gridstore}"
    },
    dockedItems: [{
      xtype: 'toolbar',
      dock: 'top',
      items: [{
        xtype: 'button',
        text: '添加用户',
        bind: {
          disabled: '{addButonDisabled}'
        },
        iconCls: "btn-add",
        listeners: {
          click: 'onAddUserButtonClick'
        }
      }, {
        xtype: 'tbfill'
      }, {
        xtype: 'textfield',
        width: 235,
        fieldLabel: '快速搜索',
        labelAlign: 'right',
        labelWidth: 60,
        emptyText: '输入用户名/邮箱/手机号',
        enableKeyEvents: true,
        listeners: {
          specialKey: 'onFastSearchTextFieldSpecialKey'
        },
        triggers: {
          fastQueryTrigger: {
            handler: 'onFastQueryButtonClick',
            cls: 'x-form-search-trigger'
          }
        },
        bind: {
          value: "{searchData.text}"
        }
      }]
    }, {
      xtype: 'pagingcustomtoolbar',
      dock: 'bottom',
      displayInfo: true,
      bind: {
        store: "{gridstore}"
      }
    }],
    columns: {
      defaults: {
        //align: "center",
        cls: 'titleAlign',
        //menuDisabled: true,
        tdCls: 'with-btngroup'
      },
      items: [{
        text: '序号',
        xtype: 'rownumberer',
        align: 'center',
        width: 37
      },{
        text: '',
        xtype: 'widgetcolumn',
        width: 300,
        tdCls: 'btngroup',
        dataIndex: 'progress',
        widget: {
          xtype: 'buttongroup',
          baseCls: "",
          layout: {
            type: "column"
          },
          defaultBindProperty: 'permission',
          setPermission: function(){
            var buttonGroup = this,
                btnArray = buttonGroup.items.items,
                record = btnArray[0].ownerCt.getWidgetRecord();

            if (Ext.Array.contains(_USER.permissions, "accountMgmt:edit")) {
              Ext.Array.each(btnArray, function(item, index) {
                if (record.get("isAdmin") && item.command == "Permission") {
                  item.setDisabled(true);
                } else if (record.get("isAdmin") && item.command == "Delete" || (item.command == "Delete" &&_USER.id == record.get('id'))) {
                  item.setDisabled(true);
                } else {
                  item.setDisabled(false);
                }
              });
            } else {
              Ext.Array.each(btnArray, function(item, index) {
                item.setDisabled(true);
              });
            }

          },
          defaults: {
            handler: "onCommandColumnClick"
          },
          items: [{
            xtype: "button",
            command: "Update",
            iconCls: "btn-edit",
            text: "信息修改"
          }, {
            xtype: "button",
            command: "Reset",
            iconCls: "btn-password-edit",
            text: "密码修改"
          }, {
            xtype: "button",
            command: "Permission",
            iconCls: "btn-permission",
            text: "权限"
          }, {
            xtype: "button",
            command: "Delete",
            iconCls: "btn-delete",
            text: "删除"
          }]
        }
      }, {
        xtype: 'gridcolumn',
        dataIndex: 'login',
        text: '用户名'
      }, {
        xtype: 'gridcolumn',
        dataIndex: 'email',
        text: '邮箱'
      }, {
        xtype: 'gridcolumn',
        dataIndex: 'mobile',
        text: '手机号'
      }, {
        xtype: 'gridcolumn',
        dataIndex: 'branchName',
        text: '分部'
      }, {
        xtype: 'gridcolumn',
        dataIndex: 'deptName',
        text: '部门'
      }, {
        xtype: 'gridcolumn',
        dataIndex: 'positionName',
        text: '职位'
      }, {
        xtype: 'checkcolumn',
        disabled: true,
        disabledCls: 'null',
        dataIndex: 'locked',
        text: '锁定'
      }, {
        xtype: 'checkcolumn',
        disabled: true,
        disabledCls: 'null',
        dataIndex: 'isAdmin',
        width: 80,
        text: '管理员'
      }, {
        xtype: 'gridcolumn',
        width: 160,
        dataIndex: 'lastLoginDate',
        formatter: 'date("Y/m/d H:i:s")',
        align: 'center',
        text: '最后登录日期'
      }, {
        xtype: 'gridcolumn',
        dataIndex: 'memo',
        text: '备注'
      }]
    },
    listeners: {
      //itemdblclick: 'onGridpanelItemDblClick'
    }
  }]
});