/*
 * File: app/view/PasswordResetDialog.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AccountMgmt.view.PasswordResetDialog', {
  extend: 'Ext.window.Window',
  alias: 'widget.passwordresetdialog',

  requires: [
    'AccountMgmt.view.PasswordResetDialogViewModel',
    'AccountMgmt.view.PasswordResetDialogViewController',
    'Common.ux.CustomVTypes'
  ],

  controller: 'passwordresetdialog',
  viewModel: {
    type: 'passwordresetdialog'
  },
  height: 154,
  width: 266,
  layout: 'fit',
  iconCls: 'permission',
  modal: true,
  title: '修改密码',

  items: [
    {
      xtype: 'form',
      reference: 'windowForm',
      border: false,
      defaults: {
        anchor: '100%',
        labelWidth: 80,
        msgTarget: 'side'
      },
      bodyPadding: 10,
      title: '',
      items: [
        {
          xtype: 'textfield',
          anchor: '100%',
          fieldLabel: '新密码<span style="color:red">*</span>',
          inputType: 'password',
          allowBlank: false,
          blankText: "请输入密码",
          name:'newPassword',
          //regex: /^[a-zA-Z\d\~\`\!\@\#\$\%\^\&\*\(\)\-\_\+\=\|\\\[\]\{\}\;\:\"\'\,\<\.\>\/\?]{6,20}$/i,
          regex: /^[\s\S]{6,20}$/i,
          regexText:'登录名长度应在6~20个字符之间，且由英文、数字及标点符号组成',
          bind: {
            value: "{formData.password}"
          }
        },
        {
          xtype: 'textfield',
          anchor: '100%',
          fieldLabel: '再次输入密码<span style="color:red">*</span>',
          inputType: 'password',
          allowBlank: false,
          blankText: "请输入密码",
          vtype:'repetitionCustom',
          repetition: {targetName: 'newPassword'},
          bind: {
          value: "{formData.confirmPassword}"
        }
        }
      ]
    }
  ],
  dockedItems: [
    {
      xtype: 'toolbar',
      dock: 'bottom',
      ui: 'footer',
      items: [
        {
          xtype: 'tbfill'
        },
        {
          xtype: 'button',
          iconCls: 'btn-save',
          text: '保存',
          listeners: {
            click: 'onSaveButtonClick'
          }
        },
        {
          xtype: 'button',
          iconCls: 'btn-cancel',
          text: '取消',
          listeners: {
            click: 'onCancelButtonClick'
          }
        }
      ]
    }
  ]

});