/*
 * File: app/view/PasswordResetDialogViewController.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AccountMgmt.view.PasswordResetDialogViewController', {
  extend: 'Ext.app.ViewController',
  alias: 'controller.passwordresetdialog',


  init: function() {
    this.getViewModel().set('formData', {
      password: "",
      confirmPassword: ""
    });
  },

  /**
   * 保存
   */
  onSaveButtonClick: function(button, e, eOpts) {
    var viewCtr = this,
        dialog = viewCtr.getView(),
        viewModel = viewCtr.getViewModel(),
        formData = viewModel.get('formData'),
        newPassword = formData.password,
        confirmPassword = formData.confirmPassword;

    if (!dialog.down('form').isValid()) {
      if (Ext.isEmpty(newPassword)) {
        TipsUtil.showTips('提示', '新密码不能为空', TipsUtil.WARING);
      }
      return ;
    }

    if (newPassword != confirmPassword) {
      TipsUtil.showTips('提示', '两次输入的密码不一致', TipsUtil.WARING);
      return ;
    }

    delete formData.confirmPassword;

    DoActionUtil.request(
      'POST',
      '/api/general/user/password/update/' + viewModel.get('pkId'),
      formData,
      function(result) {
        if (result.success) {
          dialog.close();
          TipsUtil.showTips('提示', result.data, TipsUtil.INFO);
        } else {
          TipsUtil.showTips('提示', result.error.message, TipsUtil.WARING);
        }
      }
    );
  },

  /**
   * 取消
   */
  onCancelButtonClick: function(button, e, eOpts) {
    var viewCtr = this;

    viewCtr.getView().close();
  }

});
