/*
 * File: app/view/SelectManDialog.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AccountMgmt.view.PermissionSelectManDialog', {
  extend: 'Ext.window.Window',
  alias: 'widget.permissionselectmandialog',

  requires: [
    'AccountMgmt.view.PermissionSelectManDialogViewController',
    'AccountMgmt.view.PermissionSelectManDialogViewModel',
    'AccountMgmt.store.PermissionSelectManDialogGridStore'
  ],

  height: 250,
  width: 325,
  layout: 'fit',
  bodyPadding: '',
  modal: true,
  iconCls: 'man',
  title: '选择源用户',

  controller: 'permissionselectmandialog',
  viewModel: {
    type: 'permissionselectmandialog'
  },


  items: [
    {
      xtype: 'gridpanel',
      border: false,
      title: '',
      //store: Ext.create("AccountMgmt.store.SelectManGridStore"),
      bind: {
        store: '{gridstore}'
      },
      columns: [
        {
          xtype: 'rownumberer',
          width: 38,
          align: 'center',
          text: '序号'
        },
        {
          xtype: 'gridcolumn',
          flex: 1,
          dataIndex: 'login',
          text: '<div style="text-align: center">用户名</div>'
        }
      ],
      selModel: {
        selType: 'checkboxmodel',
        //mode:"SINGLE",
        injectCheckbox: 1
      }
    }
  ],
  dockedItems: [
    {
      xtype: 'toolbar',
      dock: 'bottom',
      ui: 'footer',
      items: [
        {
          xtype: 'tbfill'
        },
        {
          xtype: 'button',
          iconCls: 'btn-save',
          text: '选择',
          listeners: {
            click: 'onSelectManSelectButtonClick'
          }
        },
        {
          xtype: 'button',
          iconCls: 'btn-cancel',
          text: '取消',
          listeners: {
            click: 'onSelectManCancelButtonClick'
          }
        }
      ]
    }
  ]

});