/*
 * File: app/view/PermissionDialogViewController.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AccountMgmt.view.PermissionSelectManDialogViewController', {
  extend: 'Ext.app.ViewController',
  alias: 'controller.permissionselectmandialog',

  /**
   * 选择
   */
  onSelectManSelectButtonClick: function() {
    var viewCtr = this,
        viewModel = viewCtr.getViewModel(),
        dialog = viewCtr.getView(),
        selectRec = dialog.down('grid').getSelectionModel().getSelection();

    if (Ext.isEmpty(selectRec)) {
      TipsUtil.showTips('提示', '未选中相关记录, 无法保存...', TipsUtil.WARING);
      return ;
    }

    var treegridstore = viewModel.get('treegridstore');

    var userIds = [];
    Ext.Array.each(selectRec, function(item) {
      userIds.push(item.get('id'));
    });

    DoActionUtil.request(
      'POST',
      '/api/general/permission/list',
      {
        userIds: userIds.join(',')
      },
      function(result) {
        if (result.success) {
          var datas = result.data;
          treegridstore.getRootNode().cascadeBy(function (node) {
            node.set('isChecked', false);
            node.commit();
          });

          var oldSelectPermissionIds = viewModel.get('oldSelectPermissionIds');
          datas = Ext.Array.map(datas, function(item) { return item.permissionId});
          datas = Ext.Array.unique(datas.concat(oldSelectPermissionIds));
          Ext.Array.each(datas, function(item) {
            var currNode = treegridstore.getNodeById(item);
            if (currNode) {
              currNode.set('isChecked', true);
              viewModel.get('permissionDialogViewController')._onCellClick( null, null, 1, currNode, null);
            }
          });

          viewModel.get('permissionDialogViewController')._refreshPermissionPanel(userIds);
          dialog.close();
        } else {
          TipsUtil.showTips('提示', result.error.message, TipsUtil.WARING);
        }
      }
    );

  },

  /**
   * 取消
   */
  onSelectManCancelButtonClick: function() {
    var viewCtr = this;
    viewCtr.getView().close();
  }
});
